# Generated by Django 3.2.7 on 2021-09-10 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_mapentrytype_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField()),
                ('short', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.mission'),
        ),
        migrations.AddField(
            model_name='mapdrawing',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='core.mission'),
        ),
        migrations.AddField(
            model_name='mapentry',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapentries', to='core.mission'),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='core.mission'),
        ),
        migrations.AddField(
            model_name='strand',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strands', to='core.mission'),
        ),
    ]
