# Generated by Django 3.2.7 on 2021-09-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210910_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapentry',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mapentry',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mapentry',
            name='short',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mapentrytype',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
