# Generated by Django 3.2.8 on 2021-10-14 11:50

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210910_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='status',
            field=computed_property.fields.ComputedCharField(compute_from='calculate_status', default='', editable=False, max_length=20),
        ),
    ]
