# Generated by Django 3.2.8 on 2021-10-28 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_entry_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='status',
        ),
    ]
