FROM node:17-alpine

ARG GIT_VERSION
ARG GIT_BRANCH
ARG GIT_LASTCOMMITDATE
ENV VITE_APP_VERSION=${GIT_VERSION}
ENV VITE_APP_BRANCH=${GIT_BRANCH}
ENV VITE_APP_LASTCOMMITDATE=${GIT_LASTCOMMITDATE}

WORKDIR /app
COPY package*.json ./
COPY yarn.lock ./
RUN npx browserslist@latest --update-db
RUN yarn install && yarn upgrade
COPY . .
CMD yarn serve --host 0.0.0.0 --port 8080